export const authTypes = Object.freeze({
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    
    VERIFY_CODE_REQUEST: 'VERIFY_CODE',
    VERIFY_CODE_SUCCESS: 'VERIFY_CODE_SUCCESS',
    VERIFY_CODE_FAILURE: 'VERIFY_CODE_FAIL',
    
    LOGOUT: 'LOGOUT',
});